# Generated by Django 3.2.6 on 2021-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210826_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'Items'), ('PB', 'Poké Balls'), ('ME', 'Medicine'), ('TM', 'TMs & HMs'), ('BE', 'Berries'), ('KI', 'Key Items')], default='IT', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
